# This is a basic workflow to help you get started with Actions

name: bootcamp_class4_2020

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Installing Node JS
      uses: actions/setup-node@v2-beta

    # Runs a set of commands using the runners shell
    - name: Intalling Surge
      run:  npm install --global surge
  
    - name: Installing Node Modules
      run: npm install

    - name : Making App Build
      run: npm run build

    - name: Deploying using Surge
      run: surge ./build bootcamp_class4_2020.surge.sh --token ${secrets.Surge_TOKEN}   
    
